# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Layout = QtWidgets.QVBoxLayout()
        self.Layout.setObjectName("Layout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.Layout.addWidget(self.label_2)
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setObjectName("input")
        self.Layout.addWidget(self.input)
        self.eng_rus = QtWidgets.QRadioButton(self.centralwidget)
        self.eng_rus.setEnabled(True)
        self.eng_rus.setAutoFillBackground(False)
        self.eng_rus.setChecked(True)
        self.eng_rus.setObjectName("eng_rus")
        self.Layout.addWidget(self.eng_rus)
        self.rus_eng = QtWidgets.QRadioButton(self.centralwidget)
        self.rus_eng.setObjectName("rus_eng")
        self.Layout.addWidget(self.rus_eng)
        self.translateBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translateBtn.sizePolicy().hasHeightForWidth())
        self.translateBtn.setSizePolicy(sizePolicy)
        self.translateBtn.setMinimumSize(QtCore.QSize(200, 50))
        self.translateBtn.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.translateBtn.setFont(font)
        self.translateBtn.setMouseTracking(False)
        self.translateBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.translateBtn.setAutoFillBackground(False)
        self.translateBtn.setStyleSheet("margin-left: 5 px;")
        self.translateBtn.setObjectName("translateBtn")
        self.Layout.addWidget(self.translateBtn)
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setStyleSheet("")
        self.output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.output.setWordWrap(True)
        self.output.setObjectName("output")
        self.Layout.addWidget(self.output)
        self.verticalLayout.addLayout(self.Layout)
        self.QuitBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuitBtn.sizePolicy().hasHeightForWidth())
        self.QuitBtn.setSizePolicy(sizePolicy)
        self.QuitBtn.setStyleSheet("")
        self.QuitBtn.setObjectName("QuitBtn")
        self.verticalLayout.addWidget(self.QuitBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Введите слово для перевода:</span></p></body></html>"))
        self.eng_rus.setText(_translate("MainWindow", "С английского на русский"))
        self.rus_eng.setText(_translate("MainWindow", "С русского на английский"))
        self.translateBtn.setText(_translate("MainWindow", "Выполнить перевод"))
        self.output.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Перевод</span></p></body></html>"))
        self.QuitBtn.setText(_translate("MainWindow", "Выход"))
